name: Rust CI
on:
  push:
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-24.04
    container: rust:1.85
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - name: Set workspace
        run: |
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
          echo "workspace=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            ${{ env.workspace }}/.cargo/bin/
            ${{ env.workspace }}/.cargo/registry/index/
            ${{ env.workspace }}/.cargo/registry/cache/
            ${{ env.workspace }}/.cargo/git/db/
            ${{ env.workspace }}/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Add rustfmt/clippy
        run: |
          rustup component add rustfmt
          rustup component add clippy
      - name: Run Cargo build
        run: cargo build
      - name: Run Cargo test
        run: cargo test
      - name: Run Cargo fmt
        run: cargo fmt --all -- --check
      - name: Run Cargo clippy
        run: cargo clippy -- -D warnings
